version: "3.5"

services:
  hbase:
    image: ${IMAGE_REPO:-diogenes1oliveira/hbase2-docker}:${IMAGE_TAG:-latest}
    extra_hosts:
      - ${HBASE_DOCKER_HOSTNAME:-localhost}:127.0.0.1
    environment:
      - HBASE_ROLE=master
      - HBASE_MANAGES_ZK=true
      - HBASE_SITE_hbase_cluster_distributed=false
      - HBASE_SITE_hbase_zookeeper_property_clientPort=${HBASE_SITE_hbase_zookeeper_property_clientPort:-2181}
      - HBASE_SITE_hbase_zookeeper_quorum=${HBASE_DOCKER_HOSTNAME:-localhost}:${HBASE_SITE_hbase_zookeeper_property_clientPort:-2181}
      - HBASE_SITE_hbase_master_port=${HBASE_SITE_hbase_master_port:-16000}
      - HBASE_SITE_hbase_master_info_port=${HBASE_SITE_hbase_master_info_port:-16010}
      - HBASE_SITE_hbase_master_hostname=${HBASE_SITE_hbase_master_hostname:-${HBASE_DOCKER_HOSTNAME:-localhost}}
      - HBASE_SITE_hbase_master=${HBASE_SITE_hbase_master_hostname:-${HBASE_DOCKER_HOSTNAME:-localhost}}:${HBASE_SITE_hbase_master_port:-16000}
      - HBASE_SITE_hbase_regionserver_port=${HBASE_SITE_hbase_regionserver_port:-16020}
      - HBASE_SITE_hbase_regionserver_info_port=${HBASE_SITE_hbase_regionserver_info_port:-16030}
      - HBASE_SITE_hbase_regionserver_hostname=${HBASE_DOCKER_HOSTNAME:-localhost}
      - HBASE_PORT_MAPPINGS
    ports:
      - ${HBASE_SITE_hbase_zookeeper_property_clientPort:-2181}:2181
      - ${HBASE_SITE_hbase_master_port:-16000}:16000
      - ${HBASE_SITE_hbase_master_info_port:-16010}:16010
      - ${HBASE_SITE_hbase_regionserver_port:-16020}:16020
      - ${HBASE_SITE_hbase_regionserver_info_port:-16030}:16030
    volumes:
      - conf:/etc/hbase/
    healthcheck:
      test: hbase2-docker-healthcheck
      interval: 15s
      timeout: 10s
      retries: 2
      start_period: 20s

  client:
    image: ${IMAGE_REPO:-diogenes1oliveira/hbase2-docker}:${IMAGE_TAG:-latest}
    entrypoint: tail
    command: -f /dev/null
    network_mode: host
    volumes:
      - conf:/etc/hbase/

volumes:
  conf:
