version: "3.5"

services:
  hbase:
    image: ${IMAGE_REPO:-diogenes1oliveira/hbase2-docker}:${IMAGE_TAG:-latest}
    extra_hosts:
      - ${HBASE2__DOCKER_HOSTNAME:-localhost}:127.0.0.1
    env_file: "${HBASE_ENV_FILE:-.env}"
    environment:
      - HBASE_COMMAND=master
      - HBASE_MANAGES_ZK=true
      - HBASE_SITE_HBASE_CLUSTER_DISTRIBUTED=false
      - HBASE_SITE_HBASE_ZOOKEEPER_PROPERTY_CLIENT___PORT=${HBASE_SITE_HBASE_ZOOKEEPER_PROPERTY_CLIENT___PORT:-2181}
      - HBASE_SITE_HBASE_ZOOKEEPER_QUORUM=${HBASE2__DOCKER_HOSTNAME:-localhost}:${HBASE_SITE_HBASE_ZOOKEEPER_PROPERTY_CLIENT___PORT:-2181}
      - HBASE_SITE_HBASE_MASTER_PORT=${HBASE_SITE_HBASE_MASTER_PORT:-16000}
      - HBASE_SITE_HBASE_MASTER_INFO_PORT=${HBASE_SITE_HBASE_MASTER_INFO_PORT:-16010}
      - HBASE_SITE_HBASE_MASTER_HOSTNAME=${HBASE_SITE_HBASE_MASTER_HOSTNAME:-${HBASE2__DOCKER_HOSTNAME:-localhost}}
      - HBASE_SITE_HBASE_MASTER=${HBASE_SITE_HBASE_MASTER_HOSTNAME:-${HBASE2__DOCKER_HOSTNAME:-localhost}}:${HBASE_SITE_HBASE_MASTER_PORT:-16000}
      - HBASE_SITE_HBASE_REGIONSERVER_PORT=${HBASE_SITE_HBASE_REGIONSERVER_PORT:-16020}
      - HBASE_SITE_HBASE_REGIONSERVER_INFO_PORT=${HBASE_SITE_HBASE_REGIONSERVER_INFO_PORT:-16030}
      - HBASE_SITE_HBASE_REGIONSERVER_HOSTNAME=${HBASE2__DOCKER_HOSTNAME:-localhost}
      - HBASE_HEALTHCHECK_PORT=${HBASE_HEALTHCHECK_PORT:-17000}
      - HBASE_POST_INITIALIZATION_COMMAND=create 'test-table', 'f'
      - >-
        HBASE_PORT_MAPPINGS=
          2181:${HBASE_SITE_HBASE_ZOOKEEPER_PROPERTY_CLIENT___PORT:-2181}
          16000:${HBASE_SITE_HBASE_MASTER_PORT:-16000}
          16010:${HBASE_SITE_HBASE_MASTER_INFO_PORT:-16010}
          16020:${HBASE_SITE_HBASE_REGIONSERVER_PORT:-16020}
          16030:${HBASE_SITE_HBASE_REGIONSERVER_INFO_PORT:-16030}
          17000:${HBASE_HEALTHCHECK_PORT:-17000}
    ports:
      - ${HBASE_SITE_HBASE_ZOOKEEPER_PROPERTY_CLIENT___PORT:-2181}:2181
      - ${HBASE_SITE_HBASE_MASTER_PORT:-16000}:16000
      - ${HBASE_SITE_HBASE_MASTER_INFO_PORT:-16010}:16010
      - ${HBASE_SITE_HBASE_REGIONSERVER_PORT:-16020}:16020
      - ${HBASE_SITE_HBASE_REGIONSERVER_INFO_PORT:-16030}:16030
      - ${HBASE_HEALTHCHECK_PORT:-17000}:17000
    volumes:
      - conf:/etc/hbase/
    healthcheck:
      test: hbase2-docker-healthcheck
      interval: 15s
      timeout: 10s
      retries: 2
      start_period: 20s

  client:
    image: ${IMAGE_REPO:-diogenes1oliveira/hbase2-docker}:${IMAGE_TAG:-latest}
    entrypoint: tail
    command: -f /dev/null
    network_mode: host
    volumes:
      - conf:/etc/hbase/

volumes:
  conf:
