name: build-docker-image
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      VCS_REF: ${{ github.ref_type == "tag" && github.ref_name || github.sha }}
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: make lint BUILD_DATE=${{ steps.date.outputs.date }}
      - run: make build BUILD_DATE=${{ steps.date.outputs.date }}
      - run: make test BUILD_DATE=${{ steps.date.outputs.date }}
