name: build-docker-image
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - run: make lint
      - run: make build
      - run: make test
