name: main
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - docker-compose.yml
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Freezes the build environment variables
        run: |
          set -eu
          export BUILD_DATE="$( date -u '+%Y-%m-%dT:%H:%M:%S.%NZ' )"
          export BUILD_VERSION="$( .dev/maven-get-version.sh )"
          make -s build/info | tee -a $GITHUB_ENV

      - name: get hosts
        run: |
          set -eux
          cat /etc/hosts
          hostname
          nslookup "$(hostname)"
          docker info
          false

      - name: Lint scripts and Dockerfile
        run: make lint

      - name: Build the Docker image
        run: make build

      - name: Run tests
        run: make test

      # based on https://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.362+9
          distribution: adopt

      - name: Replace the default image version
        run: |
          set -e
          sed -i "s|^hbase2-docker.image=.*|hbase2-docker.image=$IMAGE_NAME|g" ./src/main/resources/hbase2-docker.default.properties
          grep hbase2-docker.image ./src/main/resources/hbase2-docker.default.properties | sed 's/^/> /g'

      - name: Install and run tests
        run: mvn clean -B install

      - name: Create Git tag
        uses: rickstaa/action-create-tag@v1
        if: github.ref == 'refs/heads/main' && env.BUILD_IS_STABLE == 'true'
        with:
          tag: ${{ env.BUILD_VERSION }}
          tag_exists_error: true
          message: "release: ${{ env.BUILD_VERSION }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main' && env.BUILD_IS_STABLE == 'true'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main' && env.BUILD_IS_STABLE == 'true'
        run: make push && make push BUILD_VERSION=latest

      - name: Set up JDK 1.8 with Maven Central
        uses: actions/setup-java@v3
        if: github.ref == 'refs/heads/main' && env.BUILD_IS_STABLE == 'true'
        with:
          java-version: 8.0.362+9
          distribution: adopt
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        if: github.ref == 'refs/heads/main' && env.BUILD_IS_STABLE == 'true'
        run: mvn --batch-mode -DskipTests -DautoReleaseAfterClose=true -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Pdeploy deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
