name: main
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - docker-compose.yml
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - docker-compose.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.362+9
          distribution: adopt

      - id: version
        uses: nowsprinting/check-version-format-action@v3
        if: github.ref_type == 'tag'
        with:
          prefix: 'v'

      - name: Allow 0.x to be stable
        run: |
          echo is_stable=${{ (steps.version.outputs.is_valid && steps.version.outputs.prerelease == '') && 'true' || 'false' }} >> $GITHUB_ENV

      - name: Fail if tag doesn't match with the one in the pom.xml
        if: github.ref_type == 'tag'
        run: test '${{ github.ref_name }}' = $( make maven/version )

      - name: Set VCS_REF and BUILD_DATE
        run: |
          echo "VCS_REF=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}" > .env
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> .env
          make -s build/info

      - name: Lint scripts and Dockerfile
        run: make lint

      - name: Build the Docker image
        run: make build

      - name: Run tests
        run: make test

      - name: Login to Docker Hub
        if: github.ref_type == 'tag'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: github.ref_type == 'tag'
        run: make push

      - name: Push latest Docker image
        if: github.ref_type == 'tag' && env.is_stable == 'true'
        run: make push BUILD_VERSION=latest

      # based on https://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html

      - name: Compile code
        run: mvn -B compile -DskipTests=true

      - name: Run unit tests
        run: mvn -B test

      - name: Package
        run: mvn -B package -DskipTests=true
      
      - name: Run integration tests
        run: mvn -B verify

      - name: Set up JDK 1.8 with Maven Central
        uses: actions/setup-java@v3
        if: github.ref_type == 'tag'
        with:
          java-version: 8.0.362+9
          distribution: adopt
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        if: github.ref_type == 'tag'
        run: mvn --batch-mode -DskipTests -DautoReleaseAfterClose=${{ env.is_stable }} -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Pdeploy deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
