name: main
on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - docker-compose.yml
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - docker-compose.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Freezes the build environment variables
        run: |
          set -e
          export BUILD_DATE="$( date -u '+%Y-%m-%dT:%H:%M:%S.%NZ' )"
          make -s build/info | tee -a $GITHUB_ENV

      - name: Lint scripts and Dockerfile
        run: make lint

      - name: Build the Docker image
        run: make build

      - name: Run tests
        run: make test

      - name: Login to Docker Hub
        if: env.BUILD_IS_STABLE == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: env.BUILD_IS_STABLE == 'true'
        run: make push && make push BUILD_VERSION=latest

      # based on https://bjansen.github.io/java/2021/02/03/deploying-to-maven-central-using-github-actions.html

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.362+9
          distribution: adopt

      - name: Replace the default image version
        run: |
          set -e
          sed -i "s/:latest/:$BUILD_VERSION/g" ./src/main/resources/hbase2-docker.properties
          grep default-image ./src/main/resources/hbase2-docker.properties | sed 's/^/> /g'

      - name: Compile code
        run: mvn -B compile -DskipTests=true

      - name: Run unit tests
        run: mvn -B test

      - name: Package
        run: mvn -B package -DskipTests=true
      
      - name: Run integration tests
        run: mvn -B verify

      - name: Set up JDK 1.8 with Maven Central
        uses: actions/setup-java@v3
        if: env.BUILD_IS_STABLE == 'true'
        with:
          java-version: 8.0.362+9
          distribution: adopt
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        if: env.BUILD_IS_STABLE == 'true'
        run: mvn --batch-mode -DskipTests -DautoReleaseAfterClose=true -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }} -Pdeploy deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
