name: main
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set VCS_REF and BUILD_DATE
        run: |
          echo "VCS_REF=${{ github.ref_type == 'tag' && github.ref_name || github.sha }}" > .env
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> .env
          make -s build/info

      - name: Login to Docker Hub
        if: github.ref_type == 'tag'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Lint scripts and Dockerfile
        run: make lint

      - name: Build the Docker image
        run: make build

      - name: Run tests
        run: make test

      - name: Push Docker image
        if: github.ref_type == 'tag'
        run: make push
